AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A function that handles a Slack slash command and echoes the details back to
  the user.
Resources:
  musaic:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: >-
        A function that handles a Slack slash command and echoes the details
        back to the user.
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::029859578719:role/service-role/kmsDecrypt'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /musaic
            Method: ANY
      Tags:
        'lambda-console:blueprint': slack-echo-command-python
